// app/layout.tsx
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { Web3Provider } from '../components/Web3Provider';
import Link from 'next/link';


import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Web3Provider>
          {/* Navigation Dropdown */}
          <header className="w-full flex justify-center py-6 border-b">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">Navigate</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56">
                <DropdownMenuItem asChild>
                  <Link href="/">Home</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/about">About</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/contact">Contact</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/pricing">Pricing</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/dashboard">Dashboard</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/leaderboard">Leaderboard</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href="/rewards">Rewards</Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </header>

          {/* Page content */}
          <main className="min-h-screen px-4">{children}</main>

          {/* Social Media Footer */}
          <footer className="w-full border-t py-6 flex justify-center gap-6 items-center">
  <Link href="https://facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
      <path d="M22 12a10 10 0 1 0-11.5 9.87v-6.99H8.08v-2.88h2.42V9.5c0-2.4 1.43-3.74 3.63-3.74 1.05 0 2.15.19 2.15.19v2.36h-1.21c-1.19 0-1.56.74-1.56 1.5v1.8h2.65l-.42 2.88h-2.23v6.99A10 10 0 0 0 22 12Z" />
    </svg>
  </Link>

  <Link href="https://x.com" target="_blank" rel="noopener noreferrer" aria-label="X (Twitter)">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
      <path d="M22.5 3h-3.5l-4.9 6.4L9.5 3H2l7.8 10.4L2.3 21h3.5l5.5-7.2 5.4 7.2h7.3L17.5 10 22.5 3z" />
    </svg>
  </Link>

  <Link href="https://linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
      <path d="M4.98 3.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM2 8.98h6v13H2v-13zm7.5 0h5.6v1.78h.08c.78-1.3 2.7-2.1 4.44-2.1 4.8 0 5.68 3.16 5.68 7.26v6.06h-6v-5.36c0-1.28-.02-2.92-1.78-2.92s-2.06 1.4-2.06 2.84v5.44h-6v-13z" />
    </svg>
  </Link>

  <Link href="https://instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
      <path d="M7 2C4.24 2 2 4.24 2 7v10c0 2.76 2.24 5 5 5h10c2.76 0 5-2.24 5-5V7c0-2.76-2.24-5-5-5H7zm10 2c1.66 0 3 1.34 3 3v10c0 1.66-1.34 3-3 3H7c-1.66 0-3-1.34-3-3V7c0-1.66 1.34-3 3-3h10zm-5 3a5 5 0 1 0 .001 10.001A5 5 0 0 0 12 7zm0 2a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm4.5-.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </svg>
  </Link>
</footer>

        </Web3Provider>
      </body>
    </html>
  );
}
